### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by JaninaPi** [raspberrypilearning/scratch-cat-goes-skiing#2]
It might be nice to use collapsible hints in some of the steps towards the end:

Step 6:
- Below line 12, add something like "Use the `obstacle_x` variable in the right code blocks to set the sprite's random location."
- Add "I need a hint" hint section
- Use line 13 as the first hint, and the image as the second hint (prefaced by "This is what your code should look like:")

Step 7:
- Add "I need a hint" hint section at the bottom
- Move last image into a hint prefaced by "This is what your code should look like:"

Step 8:
- Add "I need a hint" hint section at the bottom
- Move last image into a hint prefaced by "This is what your code should look like:"

**Comment by martinohanlon** [comment]
For this project, we have purposely used less hints and provided more direct instructions. 

This is due to feedback which suggests that those at 'creator' level find the hints distracting and simply click through, it has also been suggested that new learners have found them to be demotivating as they feel that to look at a hint means they have failed.
